---
- name: Install Grafana on monitoring node
  hosts: monitoring
  become: yes

  tasks:
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - software-properties-common
          - wget
        state: present
        update_cache: yes

    - name: Create Grafana keyring directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Grafana GPG key
      shell: |
        wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | tee /etc/apt/keyrings/grafana.gpg > /dev/null
      args:
        executable: /bin/bash

    - name: Add Grafana APT repository
      copy:
        dest: /etc/apt/sources.list.d/grafana.list
        content: |
          deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main
          deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com beta main

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Enable and start Grafana service
      systemd:
        name: grafana-server
        enabled: yes
        state: started
